project:
  type: website

website:
  title: "Dr. Justin Sexton"
  page-footer:
    left: "Copyright 2022, Justin Sexton"
    right:
        - text: "Created using Quarto"
          url: https://quarto.org/docs/websites
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: info
      - href: publications.qmd
        text: Publications
      - text: Projects
        menu:
          - text: "Opticane"
            url: https://www.opticane.net
          - text: "NRM BRICZ"
            url: https://jdsextonjcu.shinyapps.io/NRM_BRICZ/
      - text: "Dengue in the Pacific"
        menu:
          - href: pic_islands_map.html
            text: "Pacific Island Countries"
          - href: interpacific_connections_chords.html
            text: "Chord Diagram Inter-Pacific Flights"
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

